CXX=		g++
CXXFLAGS=	-g -Wall -std=c++1y

TARGET = hello_world
SRC = hello_world.cpp
DEPS =

exec: hello_world makefile
	$(CXX) $(CCFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -rf *.o $(TARGET) $(TARGET).dSYM
